# Generated by Django 2.2.3 on 2019-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennismodel',
            name='time',
        ),
        migrations.AddField(
            model_name='tennismodel',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennismodel',
            name='endtime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennismodel',
            name='starttime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
