# Generated by Django 2.2.3 on 2019-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0002_auto_20190815_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennismodel',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
