# Generated by Django 2.2.3 on 2019-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0003_auto_20190815_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennismodel',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
