# Generated by Django 2.2.3 on 2019-08-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0005_auto_20190815_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennismodel',
            name='place',
        ),
    ]
