# Generated by Django 2.2.3 on 2019-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0006_remove_tennismodel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennismodel',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
