# Generated by Django 2.2.4 on 2019-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisapp', '0008_tennismodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennismodel',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
