# Generated by Django 2.2.3 on 2019-09-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='user name'),
        ),
    ]
