# Generated by Django 2.2.3 on 2019-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='user_introduction',
            field=models.TextField(blank=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ユーザ名'),
        ),
    ]
