# Generated by Django 2.2.3 on 2019-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190910_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(blank=True, choices=[(10, '男性'), (20, '女性')], null=True, verbose_name='性別'),
        ),
    ]
