# Generated by Django 2.2.3 on 2019-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_user_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, choices=[(10, '10代'), (20, '20代'), (30, '30代'), (40, '40代'), (30, '50代'), (60, '60代～')], null=True, verbose_name='年齢'),
        ),
    ]
